In [1]:
import numpy as np
import pandas as pd
potincome = pd.read_csv('PotentialIncomeByMonth_Avg.csv', encoding='ISO-8859-1')
metro_median = pd.read_csv('metromedian.csv')

In [2]:
metro_median.

           \tdate\tmetro\tmedian
0     0\t201604\tportland\t115.0
1     1\t201603\tportland\t110.0
2     2\t201602\tportland\t108.0
3     3\t201601\tportland\t106.0
4     4\t201512\tportland\t150.0
5     5\t201511\tportland\t150.0
6     6\t201510\tportland\t150.0
7     7\t201704\tportland\t127.0
8     8\t201703\tportland\t128.0
9     9\t201702\tportland\t125.0
10   10\t201701\tportland\t125.0
11   11\t201612\tportland\t120.0
12   12\t201611\tportland\t120.0
13   13\t201609\tportland\t125.0
14   14\t201607\tportland\t121.0
15   15\t201610\tportland\t120.0
16   16\t201608\tportland\t125.0
17   17\t201606\tportland\t111.0
18   18\t201605\tportland\t110.0
19   19\t201705\tportland\t119.0
20   20\t201706\tportland\t120.0
21   21\t201707\tportland\t116.0
22   22\t201804\tportland\t110.0
23   23\t201805\tportland\t110.0
24   24\t201708\tportland\t120.0
25   25\t201709\tportland\t119.0
26   26\t201710\tportland\t118.0
27   27\t201711\tportland\t120.0
28   28\t201712\tportland\t120.0
29   29\t201801\tportland\t119.0
..                           ...
194       194\t201602\tLA\t108.0
195       195\t201601\tLA\t106.0
196       196\t201512\tLA\t150.0
197       197\t201511\tLA\t150.0
198       198\t201510\tLA\t150.0
199       199\t201704\tLA\t127.0
200       200\t201703\tLA\t128.0
201       201\t201702\tLA\t125.0
202       202\t201701\tLA\t125.0
203       203\t201612\tLA\t120.0
204       204\t201611\tLA\t120.0
205       205\t201609\tLA\t125.0
206       206\t201607\tLA\t121.0
207       207\t201610\tLA\t120.0
208       208\t201608\tLA\t125.0
209       209\t201606\tLA\t111.0
210       210\t201605\tLA\t110.0
211       211\t201705\tLA\t119.0
212       212\t201706\tLA\t120.0
213       213\t201707\tLA\t116.0
214       214\t201804\tLA\t110.0
215       215\t201805\tLA\t110.0
216       216\t201708\tLA\t120.0
217       217\t201709\tLA\t119.0
218       218\t201710\tLA\t118.0
219       219\t201711\tLA\t120.0
220       220\t201712\tLA\t120.0
221       221\t201801\tLA\t119.0
222       222\t201802\tLA\t119.0
223       223\t201803\tLA\t120.0

[224 rows x 1 columns]